# Generated by Django 5.1.6 on 2026-10-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='Open Graph title')),
                ('og_description', models.CharField(blank=True, max_length=320, verbose_name='Open Graph description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Open Graph image')),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(choices=[('index, follow', 'Index, follow (default)'), ('noindex, follow', 'No index, follow'), ('index, nofollow', 'Index, no follow'), ('noindex, nofollow', 'No index, no follow')], default='index, follow', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('studio', models.CharField(blank=True, help_text='The line under the title on the card, e.g. the architect or client.', max_length=200)),
                ('cover_image', models.ImageField(blank=True, help_text='Shown on the card in the projects grid.', null=True, upload_to='projects/')),
                ('cover_alt', models.CharField(blank=True, help_text='Describes the cover image. Falls back to the title.', max_length=255)),
                ('body_heading', models.CharField(blank=True, help_text='Sub-heading above the written section.', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Use the toolbar for headings, lists, links and emphasis.')),
                ('gallery_heading', models.CharField(blank=True, help_text='Sub-heading above the row of photographs.', max_length=200)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'order'], name='projects_pr_status_b7b600_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project fact',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('image', models.ImageField(upload_to='projects/')),
                ('alt', models.CharField(blank=True, help_text='Describes the photograph. Falls back to the project title.', max_length=255)),
                ('kind', models.CharField(choices=[('carousel', 'Carousel (top)'), ('gallery', 'Gallery row (bottom)')], db_index=True, default='carousel', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project image',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
