# Generated by Django 5.1.6 on 2026-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Small line under the heading on the gallery card.', max_length=160),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='link_url',
            field=models.CharField(blank=True, help_text='Where the card goes when clicked, e.g. /collections/cove/ or a full URL. Leave empty for a card that is not a link.', max_length=500),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='title',
            field=models.CharField(blank=True, help_text='Heading on the gallery card. The first word is set in a lighter tone.', max_length=120),
        ),
    ]
