# Generated by Django 5.1.6 on 2026-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_gallery_card_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='title',
            field=models.CharField(blank=True, help_text='Name shown under the card image.', max_length=120),
        ),
    ]
