# Generated by Django 5.1.6 on 2026-10-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_seed_catalogue_card_content'),
        ('projects', '0003_gallery_title_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Send the card to a product page. Search by name, or leave it empty and use the address below instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cards', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='link_url',
            field=models.CharField(blank=True, help_text='Where the card goes when you are not linking to a product, e.g. /collections/cove/ or a full URL. Leave both empty for a card that is not a link.', max_length=500),
        ),
    ]
