# Generated by Django 5.1.6 on 2026-10-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_seed_catalogue_card_content'),
        ('projects', '0004_projectimage_product_alter_projectimage_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='link_url',
            field=models.CharField(blank=True, help_text='Where the card goes when it has no product.', max_length=500),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Search for the product this card shows. Its picture, name and line are used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cards', to='catalog.product'),
        ),
    ]
