# Generated by Django 5.1.6 on 2026-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='Open Graph title')),
                ('og_description', models.CharField(blank=True, max_length=320, verbose_name='Open Graph description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Open Graph image')),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(choices=[('index, follow', 'Index, follow (default)'), ('noindex, follow', 'No index, follow'), ('index, nofollow', 'Index, no follow'), ('noindex, nofollow', 'No index, no follow')], default='index, follow', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('announcement', 'Announcement'), ('blog', 'Blog'), ('news', 'News'), ('other', 'Other')], db_index=True, default='blog', max_length=20, verbose_name='Category')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateField(db_index=True, help_text='Used for ordering and shown on the card.')),
                ('cover_image', models.ImageField(blank=True, help_text='Shown on the card and at the top of the post.', null=True, upload_to='stories/')),
                ('cover_alt', models.CharField(blank=True, help_text='Describes the cover image. Falls back to the title.', max_length=255)),
                ('excerpt', models.TextField(blank=True, help_text='One or two lines shown on the card. Falls back to the opening of the body.')),
                ('body', models.TextField(blank=True, help_text='One paragraph per blank line.')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='stories_sto_status_386c74_idx')],
            },
        ),
    ]
