# Generated by Django 5.1.6 on 2026-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.TextField(blank=True, help_text='Use the toolbar for headings, lists, links and emphasis.'),
        ),
    ]
