# Generated by Django 5.1.6 on 2026-10-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_body_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('image', models.ImageField(upload_to='stories/')),
                ('alt', models.CharField(blank=True, help_text='Describes the photograph. Falls back to the post title.', max_length=255)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.story')),
            ],
            options={
                'verbose_name': 'Post image',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
