# Generated by Django 5.1.6 on 2026-09-21 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='header, footer, ...', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='COFUR', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Change the way you work', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Dark logo used in the header.', null=True, upload_to='site/')),
                ('logo_light', models.ImageField(blank=True, help_text='Light logo used in the footer.', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp_number', models.CharField(blank=True, help_text='International format without +, e.g. 919320461618', max_length=30)),
                ('whatsapp_message', models.CharField(blank=True, default='Hello Cofur, I would like to know more about your furniture.', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('footer_description', models.TextField(blank=True)),
                ('footer_eyebrow', models.CharField(blank=True, default="Let's build better workspaces", max_length=120)),
                ('footer_title', models.CharField(blank=True, default='We’ll help you find the\nright solution.', max_length=255)),
                ('footer_primary_cta_text', models.CharField(blank=True, default='Contact us', max_length=60)),
                ('footer_primary_cta_url', models.CharField(blank=True, default='/contact/', max_length=255)),
                ('footer_secondary_cta_text', models.CharField(blank=True, default='Download catalog', max_length=60)),
                ('footer_secondary_cta_url', models.CharField(blank=True, default='/categories/soft-seating/', max_length=255)),
                ('newsletter_text', models.CharField(blank=True, max_length=255)),
                ('copyright_text', models.CharField(blank=True, default='Copyright © {year} COFUR Pvt. Ltd. All rights reserved.', max_length=255)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True, verbose_name='X / Twitter URL')),
                ('default_meta_title', models.CharField(blank=True, max_length=255)),
                ('default_meta_description', models.CharField(blank=True, max_length=320)),
                ('default_meta_keywords', models.CharField(blank=True, max_length=255)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('default_robots', models.CharField(default='index, follow', max_length=40)),
                ('google_analytics_id', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('x', 'X'), ('whatsapp', 'WhatsApp'), ('pinterest', 'Pinterest'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(help_text='Full profile URL. Use # as a placeholder.', max_length=500)),
                ('show_in_footer', models.BooleanField(default=True)),
                ('show_on_contact', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social link',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('label', models.CharField(max_length=120)),
                ('link_type', models.CharField(choices=[('internal', 'Internal page'), ('collection', 'Collection'), ('category', 'Category'), ('product', 'Product'), ('external', 'External / custom URL'), ('none', 'No link (heading / dropdown)')], default='internal', max_length=20)),
                ('internal_page', models.CharField(blank=True, choices=[('website:home', 'Home'), ('website:about', 'About'), ('website:contact', 'Contact'), ('website:collection_list', 'Collections'), ('website:enquire', 'Enquire')], max_length=60)),
                ('external_url', models.CharField(blank=True, help_text='Full URL or a path such as /about/#team', max_length=500)),
                ('url_suffix', models.CharField(blank=True, help_text='Optional anchor/query appended to internal links, e.g. #sustainability or ?collection=pebble', max_length=120)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('css_class', models.CharField(blank=True, max_length=60)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.collection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.navigationmenu')),
            ],
            options={
                'verbose_name': 'Navigation item',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.ImageField(upload_to='library/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Bytes')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='core_media_title_486534_idx')],
            },
        ),
    ]
