# Generated by Django 5.1.6 on 2026-09-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_social_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
