# Generated by Django 5.1.6 on 2026-10-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_communications_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='internal_page',
            field=models.CharField(blank=True, choices=[('website:home', 'Home'), ('website:about', 'About'), ('website:contact', 'Contact'), ('website:collection_list', 'Collections'), ('website:catalogues', 'Catalogues'), ('website:enquire', 'Enquire')], max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='Copyright © {year} COFUR Pvt. Ltd. All rights reserved | Develop by Nivtech.', max_length=255),
        ),
    ]
