# Generated by Django 5.1.6 on 2026-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalogues_link_and_footer_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='credit_text',
            field=models.CharField(blank=True, default='Develop by Nivtech.', help_text='Shown after the copyright, separated by a bar. Leave empty to hide it.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='credit_url',
            field=models.URLField(blank=True, default='https://nivtech.co.in/', help_text='Where the credit links to. Leave empty for plain text.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='Copyright © {year} COFUR Pvt. Ltd. All rights reserved', max_length=255),
        ),
    ]
