# Generated by Django 5.1.6 on 2026-10-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_move_credit_out_of_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Shown in the footer beneath the email, e.g. +91 93204 61618.', max_length=40),
        ),
    ]
