# Generated by Django 5.1.6 on 2026-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_footer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='internal_page',
            field=models.CharField(blank=True, choices=[('website:home', 'Home'), ('website:about', 'About'), ('website:contact', 'Contact'), ('website:collection_list', 'Collections'), ('website:catalogues', 'Catalogues'), ('website:stories', 'Our Story'), ('website:enquire', 'Enquire')], max_length=60),
        ),
    ]
