# Generated by Django 5.1.6 on 2026-09-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField(blank=True, help_text='Optional highlighted quote shown before the biography.')),
                ('biography', models.TextField(blank=True, help_text='Blank lines start a new paragraph.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='team/thumbs/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Team member',
                'ordering': ['order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='team_teamme_is_acti_2b6e1b_idx')],
            },
        ),
    ]
