# Generated by Django 5.1.6 on 2026-09-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentiator',
            name='description',
        ),
        migrations.RemoveField(
            model_name='differentiator',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='category_section_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='category_section_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_mobile_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subheading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_cta_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='statement_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='why_description',
        ),
    ]
