# Generated by Django 5.1.6 on 2026-09-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_trim_home_page_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_mobile_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='how_we_work_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophy_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='recycled_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='tree_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='what_we_make_image',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='banner_mobile_image',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_description',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='map_embed_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone_heading',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='show_map',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='show_social',
        ),
        migrations.RemoveField(
            model_name='homeheroslide',
            name='mobile_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='why_mobile_image',
        ),
        migrations.RemoveField(
            model_name='homestatementline',
            name='mobile_image',
        ),
    ]
