# Generated by Django 5.1.6 on 2026-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_trim_about_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='about/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='banner_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='contact/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='homeheroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='home/hero/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='home/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='homestatementline',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='home/statement/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
    ]
