# Generated by Django 5.1.6 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_mobile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_mobile_alt',
            field=models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='banner_mobile_alt',
            field=models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)'),
        ),
        migrations.AddField(
            model_name='homeheroslide',
            name='mobile_alt',
            field=models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait or square crop, minimum 800px wide. Leave empty to reuse the desktop banner.', null=True, upload_to='about/', verbose_name='Mobile banner image (optional, shown below 768px)'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='banner_mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait or square crop, minimum 800px wide. Leave empty to reuse the desktop banner.', null=True, upload_to='contact/', verbose_name='Mobile banner image (optional, shown below 768px)'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait or square crop, minimum 800px wide. Leave empty to reuse the desktop banner.', null=True, upload_to='home/hero/', verbose_name='Mobile banner image (optional, shown below 768px)'),
        ),
    ]
