# Generated by Django 5.1.6 on 2026-09-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_banner_mobile_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='why_mobile_image',
        ),
        migrations.RemoveField(
            model_name='homestatementline',
            name='mobile_image',
        ),
    ]
