# Generated by Django 5.1.6 on 2026-09-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_drop_nonbanner_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeFeaturedProduct',
        ),
    ]
