# Generated by Django 5.1.6 on 2026-10-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_cataloguepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguepage',
            name='intro_text',
        ),
    ]
