# Generated by Django 5.1.6 on 2026-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_cataloguepage_intro_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='Open Graph title')),
                ('og_description', models.CharField(blank=True, max_length=320, verbose_name='Open Graph description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Open Graph image')),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(choices=[('index, follow', 'Index, follow (default)'), ('noindex, follow', 'No index, follow'), ('index, nofollow', 'Index, no follow'), ('noindex, nofollow', 'No index, no follow')], default='index, follow', max_length=40)),
                ('page_title', models.CharField(default='Projects', max_length=120)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('banner_mobile_image', models.ImageField(blank=True, help_text='Portrait or square crop, minimum 800px wide. Leave empty to reuse the desktop banner.', null=True, upload_to='projects/', verbose_name='Mobile banner image (optional, shown below 768px)')),
                ('banner_mobile_alt', models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)')),
                ('banner_alt', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, help_text='Optional line above the grid.', max_length=200)),
                ('empty_message', models.CharField(blank=True, default='The first project is on its way.', help_text='Shown when no project is published yet.', max_length=200)),
            ],
            options={
                'verbose_name': 'Projects page',
            },
        ),
    ]
