# Generated by Django 5.1.6 on 2026-10-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_projects_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='why_mobile_alt',
            field=models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait or square crop. Leave empty to reuse the desktop image.', null=True, upload_to='home/', verbose_name='Mobile image (optional, shown below 768px)'),
        ),
        migrations.AddField(
            model_name='homestatementline',
            name='mobile_alt',
            field=models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)'),
        ),
        migrations.AddField(
            model_name='homestatementline',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait or square crop. Leave empty to reuse the desktop image.', null=True, upload_to='home/statement/', verbose_name='Mobile image (optional, shown below 768px)'),
        ),
    ]
