# Generated by Django 5.1.6 on 2026-09-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='banner_alt',
            field=models.CharField(blank=True, help_text='Describes the banner photo for screen readers and search engines.', max_length=255, verbose_name='Banner alt text'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Full-width banner at the top of the collection page. Recommended 1536×1024 or wider.', null=True, upload_to='collections/', verbose_name='Banner image (desktop)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_mobile_image',
            field=models.ImageField(blank=True, help_text='Optional portrait crop shown on screens narrower than 768px. Falls back to the desktop banner.', null=True, upload_to='collections/', verbose_name='Banner image (mobile)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='heading',
            field=models.CharField(blank=True, help_text="Shown over the banner. Defaults to '<name> collection'. Press Enter to split it over two lines, e.g. 'Cove' / 'collection'.", max_length=200, verbose_name='Banner title'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image used on the category page and home page.', null=True, upload_to='collections/'),
        ),
    ]
