# Generated by Django 5.1.6 on 2026-09-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_collection_banner_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Sub-category', 'verbose_name_plural': 'Sub-categories'},
        ),
    ]
