# Generated by Django 5.1.6 on 2026-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_collection_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='products/mobile/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='products/mobile/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='product',
            name='hover_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='products/mobile/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='products/mobile/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='finish_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='products/finishes/mobile/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='products/gallery/mobile/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='categories/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='lifestyle_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='categories/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_mobile_image',
            field=models.ImageField(blank=True, help_text='Recommended portrait 3:4 or 4:5, at least 800px wide. Leave empty to reuse the desktop image.', null=True, upload_to='collections/', verbose_name='Mobile image (optional, shown on screens below 768px)'),
        ),
    ]
