# Generated by Django 5.1.6 on 2026-09-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_mobile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Product details mosaic only. MP4 or WebM up to 100 MB. Shown instead of the image.', null=True, upload_to='products/videos/', verbose_name='Video (optional, MP4/WebM)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo page URL, used when no video file is uploaded.', verbose_name='Video link (optional)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='For a video tile this is used as the poster frame.', null=True, upload_to='products/gallery/'),
        ),
    ]
