# Generated by Django 5.1.6 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_video_tiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card_mobile_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish_mobile_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hover_mobile_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_mobile_image',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='finish_mobile_image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='mobile_image',
        ),
        migrations.AddField(
            model_name='category',
            name='banner_mobile_alt',
            field=models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='banner_mobile_alt',
            field=models.CharField(blank=True, help_text='Used with the mobile banner; falls back to the desktop alt text.', max_length=255, verbose_name='Mobile banner alt text (optional)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait or square crop, minimum 800px wide. Leave empty to reuse the desktop banner.', null=True, upload_to='categories/', verbose_name='Mobile banner image (optional, shown below 768px)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait or square crop, minimum 800px wide. Leave empty to reuse the desktop banner.', null=True, upload_to='collections/', verbose_name='Mobile banner image (optional, shown below 768px)'),
        ),
    ]
