# Generated by Django 5.1.6 on 2026-09-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_banner_mobile_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='lifestyle_mobile_image',
        ),
    ]
