# Generated by Django 5.1.6 on 2026-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_drop_nonbanner_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='lifestyle_image',
            field=models.ImageField(blank=True, help_text='Optional lifestyle photo shown in the sub-category grid on this category page.', null=True, upload_to='categories/'),
        ),
    ]
