# Generated by Django 5.1.6 on 2026-10-01 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_lifestyle_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catalogue_pdf',
            field=models.FileField(blank=True, help_text='Shown as a download button on the home page card. Leave empty to hide the button.', null=True, upload_to='catalogues/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Catalogue (PDF)'),
        ),
    ]
