# Generated by Django 5.1.6 on 2026-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_catalogue_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_mobile_alt',
            field=models.CharField(blank=True, help_text='Describes the mobile crop. Falls back to the main image alt text.', max_length=255, verbose_name='Featured image alt (mobile)'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_mobile_image',
            field=models.ImageField(blank=True, help_text='Used in the home page Featured section below 768px, where the wide main image crops badly. Leave empty to reuse the main image.', null=True, upload_to='products/', verbose_name='Featured image (mobile)'),
        ),
    ]
