# Generated by Django 5.1.6 on 2026-10-02 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_featured_mobile_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catalogue_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order of the cards on the Catalogues page. Independent of the home page rail.', verbose_name='Catalogues page position'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_catalogues',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to keep this range off the Catalogues page without hiding it elsewhere.', verbose_name='Show on the Catalogues page'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catalogue_pdf',
            field=models.FileField(blank=True, help_text="Offered on the Catalogues page card, to preview and download. Leave empty to hide the card's download button.", null=True, upload_to='catalogues/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Catalogue (PDF)'),
        ),
    ]
