# Generated by Django 5.1.6 on 2026-10-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_seed_catalogue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catalogue_image',
            field=models.ImageField(blank=True, help_text="Shown on the Catalogues page card. Leave empty to use the category's card image.", null=True, upload_to='catalogues/', verbose_name='Catalogue card image'),
        ),
        migrations.AddField(
            model_name='category',
            name='catalogue_subtitle',
            field=models.CharField(blank=True, help_text='Small line under the title on the Catalogues page card. Leave empty to use the category subtitle.', max_length=200, verbose_name='Catalogue card subtitle'),
        ),
        migrations.AddField(
            model_name='category',
            name='catalogue_title',
            field=models.CharField(blank=True, help_text='Shown on the Catalogues page card. Leave empty to use the category name.', max_length=150, verbose_name='Catalogue card title'),
        ),
    ]
