# Generated by Django 5.1.6 on 2026-10-06 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_seed_catalogue_card_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text="Short line under the title, e.g. 'Lounge, modular & breakout'.", max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Picture on the card.', null=True, upload_to='catalogues/')),
                ('pdf', models.FileField(blank=True, help_text='The brochure itself. The card opens it in a preview and offers a download.', null=True, upload_to='catalogues/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Catalogue PDF')),
                ('category', models.ForeignKey(blank=True, help_text='Optional. Which range this catalogue covers, for sorting the list here. It does not change where the card goes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogues', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
