# Generated by Django 5.1.6 on 2026-10-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_move_catalogues_off_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catalogue_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='catalogue_order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='catalogue_pdf',
        ),
        migrations.RemoveField(
            model_name='category',
            name='catalogue_subtitle',
        ),
        migrations.RemoveField(
            model_name='category',
            name='catalogue_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_on_catalogues',
        ),
    ]
